/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package av.imageview;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name="ImageviewAndroid", id="av.imageview")
public class ImageviewAndroidModule extends KrollModule
{
	private static final String LCAT = "ImageviewAndroidModule";
	private static final boolean DBG = TiConfig.LOGD;

	@Kroll.constant 
	public static final String CONTENT_MODE_ASPECT_FILL = "centerCrop";
	
	@Kroll.constant 
	public static final String CONTENT_MODE_ASPECT_FIT = "fitCenter";

	public ImageviewAndroidModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		// put module init code that needs to run when the application is created
	}
}

